### ISSUE TITLE
geometryField != null

### ISSUE THREAD

**Issue by ccloquet** [Flexberry/Leaflet-WFST#11]
Hi,

Just to report that I have found useful to test for 

``` javascript
geometryField != null 
```

in 

``` javascript
generateLayer: function(feature)
```

so that 

``` javascript
responseToLayers: function (rawData)
```

only adds not null layers.

Otherwise, I sometimes got an error and the code stopped loading other features.

**Comment by SeregaMatin** [comment]
Fixed in [v2.0.1-beta.10](https://github.com/Flexberry/Leaflet-WFST/tree/v2.0.1-beta.10).
