### ISSUE TITLE
The library does not work with leaflet 1.0 beta 1

### ISSUE THREAD

**Issue by hrishiballal** [Flexberry/Leaflet-WFST#12]
When using with the latest leaflet 1.0 beta 1, I am getting the error below. 
![wfst error](https://cloud.githubusercontent.com/assets/1588744/8787546/b812ecec-2f2c-11e5-9635-00e8dd114c9a.png)

**Comment by kuzkok** [comment]
Yes, there are breaking changes in 1.0 release - removed L.Multi\* classes. Need rewrite toGml functions and GML format provider.

**Comment by kuzkok** [comment]
I did some work for leaflet 1.0 compatilibity. I tested it for reading data, all works.

**Comment by kuzkok** [comment]
Work with leaflet 1.0.1 e00b02b5d926666eb05fb5b33249ac4c468d99d9
