### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by robertd** [Flexberry/Leaflet-WFST#13]
~~Can you add Bower support too?~~
How do you add this lib through bower?
`bower search Leaflet-WFST`  gives no results.

**Comment by kuzkok** [comment]
done

```
>bower search Leaflet-WFST
Search results:

    Leaflet-WFST git://github.com/Flexberry/Leaflet-WFST.git
```

you also can install this lib with bower directly from repo

**Comment by robertd** [comment]
thanks
