### ISSUE TITLE
.save() callback?

### ISSUE THREAD

**Issue by robertd** [Flexberry/Leaflet-WFST#15]
How do I know if .save() succeeded or failed?

**Comment by kuzkok** [comment]
There are "save:success" event, but now this is only indicate that ajax post-request success. At this moment this is not possible to know "wfs:Transaction" succeded of failed.

**Comment by robertd** [comment]
Is there a similar "save:failed" (ajax post-request failed)? That way I can actually handle failed scenarios where the connection between my app and the service has failed?

**Comment by kuzkok** [comment]
Add error handling in ed40c9cb24f5f00758b28ec19f5f28620ae61322 and later commits
