### ISSUE TITLE
Internet Explorer doesn't support XPathEvaluator

### ISSUE THREAD

**Issue by robertdlangford** [Flexberry/Leaflet-WFST#18]
Great extension, but unfortunately I'm having problems with some users who want to use IE(?!).

https://github.com/Flexberry/Leaflet-WFST/blob/1d5b5fddd4df5299727cee387fb3e419092a4cde/dist/Leaflet-WFST.src.js#L35

This seems to be causing issues when trying to use in Internet Explorer (I tested using IE10).

From some [Googling](http://stackoverflow.com/a/12928041/2053770):

> Internet Explorer is the only browser that now doesn't support `XPathEvaluator`. You can use `selectNode()` and `selectSingleNode()` on the DOM Document object instead (IE only).

**Comment by kuzkok** [comment]
We will add support for IE in future. Or you can do it and send pull request.

**Comment by kuzkok** [comment]
not actual for IE now :)
