### ISSUE TITLE
Support: Passing CQL back to Geoserver

### ISSUE THREAD

**Issue by spydmobile** [Flexberry/Leaflet-WFST#23]
Hi, I am loving this library and am trying to push the boundries of what I can do with it, I dont seem to be able to create a CQL filter to pass back to geoserver, is this even possible?

I am trying to have the wfst load a subset of features from geoserver where the attribute "context" is 'foo' that way I can load only "foo" features from the WFS layer during the edit session. 

Thanks for any advice or assistance.
Franco

**Comment by kuzkok** [comment]
Hello, thanks for feedback. 
In future we will add more filters realization and some fixes for using its in initial data loading.
In this case "PropertyIsEqalTo" filter needed

``` xml
<Filter>
   <PropertyIsEqualTo>
     <PropertyName>SomeProperty</PropertyName>
     <Literal>100</Literal>
   </PropertyIsEqualTo>
</Filter>
```

**Comment by spydmobile** [comment]
Thank you for your response!
can I do this now with the existing code or this will be possible in the future?

**Comment by kuzkok** [comment]
At this moment initial filter is not supported. We'll add this property in future.

**Comment by spydmobile** [comment]
Cool thank you :)

**Comment by kuzkok** [comment]
added support fo initial filter in #38 and PropertyIsEqualTo in 12f49d088de2b93f538ab3b7cce7757763cc7b14
