### ISSUE TITLE
EditPopupToolbar

### ISSUE THREAD

**Issue by carrbrpoa** [Flexberry/Leaflet-WFST#27]
I'm handling WFST's click event with the following code, like I saw in examples:

``` javascript
wfst.on('click', function (event) {
    new L.EditPopupToolbar(event.latlng).addTo(map, event.layer);
});
```

The problem is that the EditPopupToolbar only appears in the first click, even debugging and seeing that the event is being fired.

Any ideas?

Thanks in advance

**Comment by kuzkok** [comment]
No idea. Can you publish full code listing?

**Comment by carrbrpoa** [comment]
Found something!

It seems to be associated with Leaflet's version: your [polygon geoJSON example](http://flexberry.github.io/Leaflet-WFST/examples/polygonGeoJSON.html) is using Leaflet 0.7.3, while I was trying at least with 1.0.0.beta.1.

The problem is that with 1.0.0.beta.1 and above (at least), the following code of your EditToolbar.js is being executed when I click a polygon after the first time:

``` javascript
map.once('click', function () { // Line 65 of EditToolbar.js
    map.removeLayer(that);
});
```

[plunkr](http://plnkr.co/edit/iN00VsQbmr4eps3w65rt?p=preview) with 1.0.0.beta.1 and your sample data. See how it works when you change to 0.7.3.

**Comment by carrbrpoa** [comment]
It's an [expected behaviour](https://github.com/Leaflet/Leaflet/issues/4258).

So, the following modification in EditToolbar.js keeps the popup working as expected:

``` javascript
map.once('click', function (e) {
    map.removeLayer(that);
});
shape.once('click', function (e) {
    map.removeLayer(that);
    L.DomEvent.stopPropagation(e);
});
```
