### ISSUE TITLE
Problems importing WFS with Leaflet 0.7.7

### ISSUE THREAD

**Issue by ismail44** [Flexberry/Leaflet-WFST#28]
I am having problems getting WFS layers to appear on my map. I am using Leaflet version 0.7.7
and I am using layers from: 

http://demo.opengeo.org/geoserver/wfs

I have tried just about every layer they support. 

I get a plethora of different errors:

> TypeError: hole is undefined
> {domain}/assets/leaflet.self-45659c657e1c7526f5ad36ed2ca57f9d2689bfcb5c96bc84e276d8b9a9e477b0.js?body=1
> Line 5669
> 
> TypeError: latlngs is undefined
> {domain}/assets/leaflet.self-45659c657e1c7526f5ad36ed2ca57f9d2689bfcb5c96bc84e276d8b9a9e477b0.js?body=1
> Line 5678

The XML looks like it's coming back just fine... is there a playground or sandbox I can use to provide a firm example?

Here is my example call:

`var oceans = new L.WFS({
                url: 'http://demo.opengeo.org/geoserver/wfs',
                typeNS: 'maps',
                typeName: 'ocean',
                crs: L.CRS.EPSG4326,
                                geometryField: 'the_geom'
            }).addTo(map);`

Here is the response from my call:

`<wfs:FeatureCollection xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:nasa="http://nasa.gov" xmlns:ogc="http://www.opengis.net/ogc" xmlns:maps="http://boundlessgeo.com" xmlns:topp="http://www.openplans.org/topp" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ne="http://naturalearthdata.com" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gml="http://www.opengis.net/gml" xmlns:osm="http://openstreemap.org" xmlns:nurc="http://www.nurc.nato.int" xmlns:og="http://opengeo.org" xmlns:usgs="http://www.usgs.gov/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" numberOfFeatures="1" timeStamp="2016-03-01T16:12:47.132Z" xsi:schemaLocation="http://boundlessgeo.com http://demo.opengeo.org:80/geoserver/wfs?service=WFS&version=1.1.0&request=DescribeFeatureType&typeName=maps%3Aocean http://www.opengis.net/wfs http://demo.opengeo.org:80/geoserver/schemas/wfs/1.1.0/wfs.xsd">
<gml:boundedBy>
<gml:Envelope srsDimension="2" srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
<gml:lowerCorner>-180.0 -90.0</gml:lowerCorner>
<gml:upperCorner>180.0 90.0</gml:upperCorner>
</gml:Envelope>
</gml:boundedBy>
<gml:featureMembers>
<maps:ocean gml:id="ocean.1">
<gml:boundedBy>
<gml:Envelope srsDimension="2" srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
<gml:lowerCorner>-180.0 -90.0</gml:lowerCorner>
<gml:upperCorner>180.0 90.0</gml:upperCorner>
</gml:Envelope>
</gml:boundedBy>
<maps:the_geom>
<gml:MultiSurface srsDimension="2" srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
<gml:surfaceMember>
<gml:Polygon srsDimension="2">
<gml:exterior>
<gml:LinearRing srsDimension="2">
<gml:posList>-180.0 -90.0 -180.0 90.0 180.0 90.0 180.0 -90.0 -180.0 -90.0</gml:posList>
</gml:LinearRing>
</gml:exterior>
</gml:Polygon>
</gml:surfaceMember>
</gml:MultiSurface>
</maps:the_geom>
<maps:featurecla>Ocean</maps:featurecla>
</maps:ocean>
</gml:featureMembers>
</wfs:FeatureCollection>`

Thanks.

**Comment by ismail44** [comment]
As I inspect this GML a bit further, it looks like it's just a Polygon that's supposed to be around the entire map? Is this something that this plugin or leaflet should address?

**Comment by kuzkok** [comment]
I did [jsbin for playing](http://jsbin.com/quceke/edit?html,js,output) - all works as expected.
Suppose it was same error as in #29
