### ISSUE TITLE
Using OGC Filter realization:

### ISSUE THREAD

**Issue by teguh87** [Flexberry/Leaflet-WFST#30]
Hi anyone has used this library show me how to use OGC Filter realization

Thank's

**Comment by kuzkok** [comment]
[filterBBox](https://github.com/Flexberry/Leaflet-WFST/blob/master/examples/filterBBox.htmlmaster/examples/filterBBox.html)

a7f1fc4a0412c0bd30a1b9567fd412b05f0db34e
