### ISSUE TITLE
как пользоваться typeNS:

### ISSUE THREAD

**Issue by gornak49** [Flexberry/Leaflet-WFST#33]
геосервер (облачный веб сервис)выдает данные без префикса NameSpace
GetCapabilinies:
FeatureTypeList Operations Query Operations FeatureType  **Name>kvly</Name**  Title kv:kv Title  Abstract SRS>EPSG:3857</SRS

как в таком случае подключать  WFS?

**Comment by kuzkok** [comment]
Ссылку бы на него получить, или весь GetCapabilities

**Comment by gornak49** [comment]
вот ссылки на два сервиса:
http://vvlph.nextgis.com/api/resource/6/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetCapabilities

http://wms.qgiscloud.com/gornak/ls_1?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetCapabilities

по поводу первого мне уже дали такой ответ(что дело в CORS):
http://gis-lab.info/forum/viewtopic.php?f=19&t=21262

**Comment by kuzkok** [comment]
WMS не использует POST запросы, поэтому и работает без проблем. 
У нас уже просили добавить возможность прокси запросов к сервисам без включенного CORS (#25), но мы пока до этой задачи не добрались.
