### ISSUE TITLE
Network error in IE/Edge

### ISSUE THREAD

**Issue by QbyteFennek** [Flexberry/Leaflet-WFST#39]
Hello,

SCRIPT7002: XMLHttpRequest: Network Error 0x2f78, Could not complete the operation due to error 00002f78.

I get this error in IE/edge. In Chrome and Firefox it works fine.

```
var DBA_spatial = new L.WFST({
        crs: crs,
        geometryField: 'location',
        url: 'http://192.168.1.169:1112/eoswfs?service=WFS',
        typeNS: 'orbit',
        typeName: 'DBA__1',
        maxZoom: 20,
        minZoom: 1,
    });
```

**Comment by kuzkok** [comment]
Error is not concern to this repo code.
