### ISSUE TITLE
Support for GML Simple Features Profile

### ISSUE THREAD

**Issue by FilmCoder** [Flexberry/Leaflet-WFST#40]
Does this library support the GML Simple Features Profile, as can be seen on Wikipedia?

https://en.wikipedia.org/wiki/Geography_Markup_Language#GML_Simple_Features_Profile

Thank you!

**Comment by kuzkok** [comment]
Simple Feature Profile is a [profile of OGC GML Standard](http://portal.opengeospatial.org/files/?artifact_id=15201). This library implementation is close to some subset of this standard SF-0, and mostly correspond to wiki information.
