### ISSUE TITLE
Saving Date properties

### ISSUE THREAD

**Issue by asavartsov** [Flexberry/Leaflet-WFST#44]
Saving shapes with Date properties doesn't work at least with my Geoserver 2.10.0 installation. The library successfully parses dates from WFS service, but when I try to save such feature, I get the following response:
    
    Update error: java.lang.String cannot be cast to java.sql.Date

The property in generated transaction request looks like this:

    <wfs:Property><wfs:Name>DateCreation</wfs:Name><wfs:Value>Tue Sep 13 1983 03:00:00 GMT+0300 (Russia TZ 2 Standard Time)</wfs:Value></wfs:Property>

**Comment by arszp10** [comment]
Тоже сталкивался с такой проблемой.
Дело в том, что дата в плагине формируется так [/src/Format/Parsers/FeatureType.js](https://github.com/Flexberry/Leaflet-WFST/blob/ca82cce7f016c19a9381341fded8a45fbf148724/src/Format/Parsers/FeatureType.js#L32)
И зависит этот конструктор от локали. Например у меня `new Date('2016-12-22')` вернёт строку `"Thu Dec 22 2016 03:00:00 GMT+0300 (MSK)"`.
Когда идёт сохранение, то эта строка передаётся, но на это geoserver выдаёт ошибку.
Потому что он ожидает дату в формате `YYYY-MM-DD` [xsd:date](http://www.w3schools.com/xml/schema_dtypes_date.asp)
Нужно перед сохранением форматировать дату.

Помимо этого бага находил ещё несколько. Я собираюсь написать исправление этих багов с тестами, но будет это неизвестно когда (в пределах 6 месяцев, если повезёт :smile:)
