### ISSUE TITLE
use circle in Intersects filter(except Marker、Polygon、Polyline、MultiPolygon、MultiPolyline、LatLngBounds)?

### ISSUE THREAD

**Issue by ailong** [Flexberry/Leaflet-WFST#46]
can i  use circle in Intersects filter(except Marker、Polygon、Polyline、MultiPolygon、MultiPolyline、LatLngBounds)?how?

**Comment by arszp10** [comment]
short answer: no way
at the moment plugin dont realization L.CircleMarker.toGML
you should be convert circle to polygon
