### ISSUE TITLE
Доработать создание файла min

### ISSUE THREAD

**Issue by kuzkok** [Flexberry/Leaflet-WFST#5]
Добавить файлы /dist/ в контроль версий, удостовериться в корректной сборке файла min, проверить установку в bower

**Comment by kuzkok** [comment]
44567f40154392a8c593fb866c5754f24ad8e6cc

**Comment by SeregaMatin** [comment]
Минифицированная версия собирается корректно.
Пакет для bower пока не регистрировал.
