### ISSUE TITLE
Publish to npmjs.com

### ISSUE THREAD

**Issue by pauldaustin** [Flexberry/Leaflet-WFST#50]
Any plans to deploy releases to npmjs.com?

https://docs.npmjs.com/misc/developers

**Comment by ehaberev** [comment]
We released and published current version ([v1.1.1](https://github.com/Flexberry/Leaflet-WFST/releases/tag/v1.1.1)) of the plugin to npmjs.com and bower.io as [`leaflet-wfst`](https://www.npmjs.com/package/leaflet-wfst) package.
Now you can install package
Via [npm](https://www.npmjs.com/):
```
npm i leaflet-wfst --save
```
Via [Bower](https://bower.io/):
```
bower i leaflet-wfst --save
```
