### ISSUE TITLE
Does Leaflet-WFST-Layer store Attributes?

### ISSUE THREAD

**Issue by gis1234** [Flexberry/Leaflet-WFST#68]
During a study project I created a WFS-T service unsing Geoserver and a PostGIS Database (for storing the data). Now I would like to create a Leaflet application that allows users to edit the features of the WFST. Not only the geometry should be editable, also the attributes of the features. 
To edit the attributes I found the part "Layer properties" in the documentation. So my first step was to create a popup showing some text, when a feature in the map is clicked. The result was what I expected. So in the next step i tried to replace the text in the popup with a number from the attributefield 'Count' using the method "getProperty('Count'). After that change I got an errormessage saying "Uncaught TypeError: cannot read property 'getProperty' of undefined". I interpreted this message as: Attributes are not saved in the layer so the method can't get an attribute with the fieldname 'Count' because it is not defined.
So my question is: Are the attributes not saved automatically if I create a new WFST-Layer? And if they are, how is it possible to get the attributes?

Here is an minimalistic version of my used sourcecode:
<html>
    <head>
        ...
    </head>
    <body>

	  <div id="mapid" style="width: 800px; height: 800px;"></div>

	  <script>

	      //creating map
	      var mymap = L.map('mapid').setView([51.14, 8.01], 11);

	      //adding WFST-Layer
	      var testWFST = new L.WFST({
                    url: 'http://localhost:8080/geoserver/TEST/ows?',
                    typeNS: 'TEST',
                    typeName: 'Testshape',
                    style: {
                         color: 'blue',
                         weight: 2
                    },
                    geometryField: 'geometrie'
                  }).addTo(mymap).once('load', function(){
                    mymap.fitBounds(testWFST);
                    testWFST.enableEdit();
                  });

	      //open Popup with attributes, when map is clicked
	      mymap.on('click', function(e){
                    mymap.openPopup(e.layer.getProperty('Anzahl'));	//Errormessage referencing to this line
              });
          </script>

</html>

**Comment by kuzkok** [comment]
For access layer property you should use click event of layer, not map. example in #8
