### ISSUE TITLE
BindPopup to Layer

### ISSUE THREAD

**Issue by mtravis** [Flexberry/Leaflet-WFST#8]
Hi there

Thanks for the plugin. I've been testing it out and it works great. 

I'm finding it difficult to add a popup to the layer using. Is this possible with the plugin. 

Here is the code for my layer

```
var boundary = new L.WFS({
url: 'http://10.0.1.218/geoserver/nd_test/ows',
typeName: 'Boundary_region',
crs: L.CRS.EPSG4326,
geometryField:'geom'
},new L.Format.GeoJSON({crs: L.CRS.EPSG4326})
).addTo(map)
.on('load', function () {
map.fitBounds(boundary);    
});
```

**Comment by kuzkok** [comment]
Hello.
WFS layer extends L.FeatureGroup layer and have all its methods and events. You can use [.bindPopup](http://leafletjs.com/reference.html#featuregroup-bindpopup) or [onclick](http://leafletjs.com/reference.html#featuregroup-click) event as in [quick start guid](http://leafletjs.com/examples/quick-start.html). I check this and its work

``` javascript
var boundary = new L.WFS().addTo(map).bindPopup('I am popup')
```

or

``` javascript
var popup = new L.Popup();
boundaries.on('click', function(e){
  popup
    .setLatLng(e.latlng)
    .setContent('You clicked on boundary layer at '+ e.latlng.toString())
    .openOn(map);
});
```

Also you can use [Leaflet.ToolBar](https://github.com/Leaflet/Leaflet.toolbar) plugin as we did in [polygon example](http://flexberry.github.io/Leaflet-WFST/examples/polygon.html)

**Comment by mtravis** [comment]
Thanks for getting back to me.

I actually tried .bindPopup(feature.properties.id) but the console gave
an error saying:

```
Uncaught ReferenceError: feature is not defined
```

Is it possible to access features properties?

**Comment by mtravis** [comment]
It appears not, as its a FeatureGroup and has a shared bindPopup method. 

Is there a way of getting the data into a L.geoJson layer?

**Comment by kuzkok** [comment]
There is no way to get L.geoJson layer in this plugin. You can access to layer feature in onclick event:

``` javascript
 boundary.on('click', function (e) {
    popup
      .setLatLng(e.latlng)
      .setContent('You clicked at '+ e.layer.feature.id)
      .openOn(map);
  });
```

but now it's not work with "Multi" classes such as MultiCurve and MultiSurface

**Comment by mtravis** [comment]
That's great thanks. Exactly what I needed.

**Comment by kuzkok** [comment]
example at http://flexberry.github.io/Leaflet-WFST/examples/popup.html
