### ISSUE TITLE
Getting 401 error

### ISSUE THREAD

**Issue by UooVeee** [Flexberry/Leaflet-WFST#82]
How to pass username and password to the WFS Service?

**Comment by kuzkok** [comment]
You can try do it by set [basic access header](https://en.wikipedia.org/wiki/Basic_access_authentication) in options.headers property something like
```
var base64login = window.btoa(user+':'+password);
var wfst = new L.WFST({
    ....
    headers: {
       Authorization: "Basic "+base64login
    }
  })

```
but it is not elegant. 
Always we use separated login in geoserver (may be by SSO), and work by browsers cookie auth.
