### ISSUE TITLE
need multi-filter,it seems that wfst don't support。

### ISSUE THREAD

**Issue by bation** [Flexberry/Leaflet-WFST#83]
I know someone has an issue about this ,but until now wfst still do not support multi-filter,I don't understand why,it's very usefull .if we don't support ,I have to get jsons and filter myself with for & if statement,that's ugly,beleave me.

**Comment by kuzkok** [comment]
Duplicate of #48 
Multi-filter exists in develop branch and beta releases.

**Comment by kuzkok** [comment]
multi filter exists in develop branch and beta releases
