### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by ErcinDedeoglu** [Flexberry/Leaflet-WFST#84]
When I try this code I'm getting error. I attached the xml file.

[xml.txt](https://github.com/Flexberry/Leaflet-WFST/files/3421827/xml.txt)

```
new L.WFS({
    url: 'xml.txt',
    typeNS: 'topp',
    typeName: 'tasmania_state_boundaries',
    crs: L.CRS.EPSG4326,
    style: {
        color: 'blue',
        weight: 2
    }
}).addTo(map)
  .on('load', function () {
      map.fitBounds(boundaries);
  })
```

```
setFeatureDescription: function (featureInfo) {
    this.namespaceUri = featureInfo.attributes.targetNamespace.value;
```

targetNamespace.value == null.
"Uncaught TypeError: Cannot read property 'value' of undefined"

**Comment by ErcinDedeoglu** [comment]
@kuzkok can you help please?

**Comment by kuzkok** [comment]
Sorry for very long aswer. At now  plugin support only full standard of WFS protocol. Before load data it do request to DescribeFeatureType, and expect special XML on response. Is is will be possible after #49 is done, but when it will be, I dont know.
Also there is something wrong with gml in xml.txt, it looks like generated by GMLv2 standard, but it is not supported.
And also not all primitives from GMLv3 supported - LinearRing not in list.
